# Generated by Django 2.2.24 on 2023-11-21 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20231121_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.IntegerField(db_index=True, verbose_name='Номер квартиры')),
                ('claim_text', models.TextField(verbose_name='Текст жалобы')),
                ('user', models.ForeignKey(on_delete='Кто жаловался?', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
