# Generated by Django 2.2.24 on 2023-11-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20231122_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='flat_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Flat', verbose_name='Номер квартиры'),
        ),
    ]
