# Generated by Django 2.2.24 on 2023-11-22 16:49

from django.db import migrations
import phonenumbers
from django.db import transaction


def parse_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = f'{phonenumber.country_code}{phonenumber.national_number}'
        else:
            flat.owner_pure_phone = None
        flat.save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20231122_1942'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumber)
    ]
