# Generated by Django 2.2.24 on 2023-11-27 21:43

from django.db import migrations


def load_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner_name=flat.owner, defaults={
            'owners_phonenumber': flat.owners_phonenumber,
            'owner_pure_phone': flat.owner_pure_phone
        })
        owner.flats.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20231128_0043'),
    ]

    operations = [
        migrations.RunPython(load_owners)
    ]
