# Generated by Django 2.2.24 on 2023-12-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20231206_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='flat_number',
            new_name='flat',
        ),
    ]
