# Generated by Django 2.2.24 on 2023-12-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_auto_20231215_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_text',
            new_name='text',
        ),
    ]
